services:
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - database/migrations/:/docker-entrypoint-initdb.d/
  backend:
    depends_on:
      - database
    build: ./backend
    environment:
      PORT: ${PORT}
    ports:
      - "3000:3000"

  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "80:80"

volumes:
  db-data: 